from aiogram.types import ReplyKeyboardRemove, \
    ReplyKeyboardMarkup, KeyboardButton, \
    InlineKeyboardMarkup, InlineKeyboardButton

#📤Choose the cryptocurrency you want to give
monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)



#📤Choose the cryptocurrency you want to get
monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_monxmr = InlineKeyboardMarkup().add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_usdttrx = InlineKeyboardMarkup().add(monxmr).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_atomcosmos = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_solanasol = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_cardanoada = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_trontrx = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_dogecoindoge = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(avalancheavax).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_avalancheavax = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(busdbnb).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_busdnb = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(usdteth).add(back)

monxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
usdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
atomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='atomcosmos2')
solanasol = KeyboardButton("SOLANA - SOL", callback_data='solanasol2')
cardanoada = KeyboardButton("CARDANO - ADA", callback_data='cardanoada2')
trontrx = KeyboardButton("TRON - TRX", callback_data='trontrx2')
dogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
avalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='avalancheavax2')
busdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='busdbnb2')
usdteth = KeyboardButton("USDT - ETH ", callback_data='usdteth2')
back = KeyboardButton("Go to the back menu!", callback_data='back')
list_crypto_usdteth = InlineKeyboardMarkup().add(monxmr).add(usdttrx).add(atomcosmos).add(solanasol).add(cardanoada).add(trontrx).add(dogecoingdoge).add(avalancheavax).add(busdbnb).add(back)