from aiogram.types import ReplyKeyboardRemove, \
    ReplyKeyboardMarkup, KeyboardButton, \
    InlineKeyboardMarkup, InlineKeyboardButton

#📤Выберите криптовалюту, которую хотите подарить
rumonxmr = KeyboardButton("Monero-XMR", callback_data='rumonxmr')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='ruusdttrx')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)



#📤Выберите криптовалюту, которую хотите получить
rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_monxmr = InlineKeyboardMarkup().add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_usdttrx = InlineKeyboardMarkup().add(rumonxmr).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_atomcosmos = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_solanasol = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_cardanoada = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_trontrx = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_dogecoindoge = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(ruavalancheavax).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_avalancheavax = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(rubusdbnb).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_busdnb = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(ruusdteth).add(ruback)

rumonxmr = KeyboardButton("Monero-XMR", callback_data='monxmr2')
ruusdttrx = KeyboardButton("USDT-TRX", callback_data='usdttrx2')
ruatomcosmos = KeyboardButton("ATOM - COSMOS", callback_data='ruatomcosmos2')
rusolanasol = KeyboardButton("SOLANA - SOL", callback_data='rusolanasol2')
rucardanoada = KeyboardButton("CARDANO - ADA", callback_data='rucardanoada2')
rutrontrx = KeyboardButton("TRON - TRX", callback_data='rutrontrx2')
rudogecoingdoge = KeyboardButton("DOGECOIN - DOGE", callback_data='dogecoindoge2')
ruavalancheavax = KeyboardButton("AVALANCHE - AVAX", callback_data='ruavalancheavax2')
rubusdbnb = KeyboardButton("BUSD - BNB SMART CHAIN", callback_data='rubusdbnb2')
ruusdteth = KeyboardButton("USDT - ETH ", callback_data='ruusdteth2')
ruback = KeyboardButton("Вернуться в главное меню!", callback_data='ruback')
ru_list_crypto_usdteth = InlineKeyboardMarkup().add(rumonxmr).add(ruusdttrx).add(ruatomcosmos).add(rusolanasol).add(rucardanoada).add(rutrontrx).add(rudogecoingdoge).add(ruavalancheavax).add(rubusdbnb).add(ruback)